= Clojure made easy
:copyright: Yehonathan Sharvit
:license: Eclipse Public License http://www.eclipse.org/legal/epl-v10.html
include::slide.attrs[]


[state=title]
== Clojure made easy


[NOTE.speaker]
This text will only show in the speaker view mode.


== Begin with the End in Mind

. You are motivated to learn Clojure
. You look differently at your existing Software knowledge 
. You had a fun evening
. You want to read my book on Clojure

== Three key ideas

. The power of expressions
. Dealing with data is valuable
. Pure functions are helpful


== The lack of power of expressions

We cannot assign the result of an `if` statement to a variable.

We cannot comment out an expression.

The syntax is not uniform: operator, statements, function calls, function definition, classes...

== The power of expressions

Every part of the language is an expression, with the same structure

Arithmetic operations
[source.eval-clojure, clojure]
(+ 1 2)

Boolean operations
[source.eval-clojure, clojure]
(and true false)

Namespace declaration
[source.eval-clojure, clojure]
(ns fun.clj)

Variable assignments
[source.eval-clojure, clojure]
(def my-num 42)

If expressions
[source.eval-clojure, clojure]
(if my-num "happy" "sad")

Function calls
[source.eval-clojure, clojure]
(inc 42)

Function definitions
[source.eval-clojure, clojure]
--
(defn add-42 [x]
  (+ x 42))
--

== The power of expressions - if expressions

We can assign the result of an `if` expression into a variable

[source.eval-clojure, clojure]
--
(def my-mood (if my-num "happy" "sad"))
my-mood
--

== The power of expressions - comments

We can comment out a single expression out of a big piece of code
[source.eval-clojure, clojure]
--
(defn print-moods [num]
  (println "happy")
  (if (= num 42)
    (println "furious")
    (println "angry"))
  (println "sad"))

(print-moods 42)
--



== Next

[source.eval-clojure, clojure]
(+ 1 2)

TIP: Try changing the numbers in the top box.
The answer in the bottom box is evaluated immediately.


== JavaScript

[source.eval-javascript, javascript]
1 + 2

NOTE: Multiple languages are supported by Klipse


== HTML

[source.eval-html, html]
<svg>
  <circle fill="blue"
          r="20" cx="50" cy="50" />
  <circle fill="green"
          r="20" cx="200" cy="50" />
</svg>

TIP: Try changing one of the colors


== What is Klipse?

An interactive client-side code evaluator.

Turns `<pre><code> ... </code></pre>` snippets into a live editor,
with beautiful syntax highlighting.

Supports many languages.

Perfect for blogs... and slides!

See the https://github.com/viebel/klipse[Klipse github repo, role="external", window="_blank"].


== What is AsciiDoctor?

A powerful toolchain for publishing.

Better than markdown:

* Target multiple formats (html/pdf/book/slides)
* Tables, figures, tip/warn/note, table of contents

See https://asciidoctor.org/[Asciidoctor, role="external", window="_blank"] for more information.


== What is RevealJS?

A modern HTML slide presentation framework.

Features include:

* Speaker notes and full screen
* Transitions
* And much more

Read more on the https://revealjs.com/[RevealJS website, role="external", window="_blank"].

== Putting it all together...

This presentation is a template project for creating your own presentation.

Get the source:

https://github.com/timothypratley/asciidoctor-revealjs-klipse[asciidoctor-revealjs-klipse github repository, role="external", window="_blank"].
