= Klipse for Clojure
:encoding: utf-8
:navigation:
:deckjs_transition: horizontal-slide
:menu:
:status:
:deckjs_theme: none
:hardbreaks:


== Klipse: The features

[%step]
- code is evaluated as you type (configurable)
- environment is shared between code snippets
- hidden code snippets
- snippet preamble	
- printing
- supports many languages: clojure, javascript (es7, jsx, react), ruby, python, brainfuck, scheme...
- clojurescript transpilation
- code evaluation in a loop
- load code from a github gist
- interacting with the DOM
- the CodeMirror editor is configurable: options and CSS

[%step]
- caching of external libs: core.async
- custom external libraries
- limited size printing
- infinite loop partial prevention
- reagent snippets
- output is beautified and strings are beautified


== Running code in a loop

[%step]
--
Let's create a klipse snippet that is evaluated again and again in intervals.

Setting `data-loop-msec` to the time in msec between the evaluations.
--

[%step]
--
For example, this is how we display a random number each second (Check the page source!):
[.text]
----
<pre><code class="lang-eval-clojure" data-loop-msec="1000">
(rand)
</code></pre>
----
--

[%step]
--
This snippet is evaluated each second - without any user interaction:
++++
<pre><code class="clj" data-loop-msec="1000">
(rand)
</code></pre>
++++
--

== Hiding some details from the reader

[%step]
--
> Less is more


You don't want to confuse your readers with technical details that are not revelant to the main idea of your article.

But you need this (irrelevant) code to let the other parts of the code run properly.
--

[%step]
--
Two mechanisms for hiding code from the reader but not from Klipse:
- A hidden Klipse snippet
- `data-preamble`
--


[%step]
--
You can hide a snippet using CSS
[.text]
----
<pre class="hidden"><code class="clj">
(def irrelevant-constant
42)
</code></pre>
----
++++
<pre class="hidden"><code class="clj">
(def irrelevant-constant  42)
</code></pre>
<p style="font-style:italic; color: blue">
There is a hidden Klipse snippet just above me
</p>
++++


We can use the hidden code in subsequent klipse snippets:
[source.clj]
----
irrelevant-constant
----
--

[%step]
--
We can hide part of the Klipse snippet's code using `data-preamble`.
[.text]
----
<pre><code class="clj" data-preamble="(def random-num  (rand))">
random-num
</code></pre>
----
--

[%step]
--
++++
<pre><code class="clj" data-preamble="(def random-num (rand))">
random-num
</code></pre>
++++
--

== Caching of clojure libs

[%step]
--
clojure libs cached in Klipse:

- core.async
- core.match
- clojure.spec
- clojure.math.combinatorics
- reagent
- reagent-froms
- clojure.test.check
- net.cgrand.macrovich
--

[%step]
--
Let's require `core.async`
[source.clj]
----
(require '[clojure.core.async :refer [chan <! timeout put!]])
(require-macros '[cljs.core.async.macros :refer [go]])
----
--

[%step]
--
Let's create a communication channel

[source.clj]
----
(def msg-chan (chan))
----

A consumer:
++++
<pre><code class="clj" data-eval-idle-msec="99999999999">
(let [container js/klipse-container]
  (go
    (let [div (js/document.createElement "div")]
      (.appendChild container div)
      (set! (.-innerText div) 
            (&lt;! msg-chan))))) 
</code></pre>
++++

A publisher
[source.clj]
----
(put! msg-chan "Hello")
----
--

[%step]
--
Check this http://app.klipse.tech/?container&cljs_in.gist=viebel/c229fbca8e6d89b2695f1849b5127e93[amazing demo] by the author of `core.async`.
--

== Clojure.libs - math.combinatorics and core.match

Let's generate all the permutations of an array

[source.clj]
----
(require '[clojure.math.combinatorics :refer [permutations]])
----
[source.clj]
----
(permutations [1 2 3])
----

[%step]
--
Here is a http://blog.klipse.tech/clojure/2016/09/16/combinatorics-riddle.html[not so easy riddle that one could solve with permutations]
--

[%step]
--
`Core.match` - pattern matching - will simplify a lot your code and make it much more elegant.
--

[%step]
--
[source.clj]
----
(require '[cljs.core.match :refer-macros [match]])
----
[source.clj]
----
(let [x 1 y 2]
  (match [x y]
         [1 b] b
         [a 2] a
         :else nil))
----
--

[%step]
Here is an http://blog.klipse.tech/clojure/2016/10/25/core-match.html[interactive tutorial of core.match]

== External libs

[%step]
--
You can also include code from an external lib, that is not cached in Klipse.

Klipse can load code dynamically from any source or code repository e.g. github.

`data-external-libs` is like the class path.
--

[%step]
--
For instance, let's play with a https://github.com/krisajenkins/original-lisp[clojure implementation of McCarthy's LISP].

++++
<pre><code class="clj" data-external-libs="https://raw.githubusercontent.com/viebel/original-lisp/48badc99b6e7cfba7b86742d2a0b9ccc5db18953/src">
(require '[original-lisp.core :refer [l-eval]])
</code></pre>
++++

[source.clj]
----
(l-eval '(car '(10 2)) '())
----
--
== Load code from a github gist

[%step]
--
Sometimes, you don't want to keep your code in the source of your blog but rather have it in a github gist.
It will allow you to modify the code of the snippet without having to republish your gitbook.
--

[%step]
--
Here is a gist that defines a function `read-several-exps` for reading several expressions from a string.
(`read-string` reads only a single expression)
++++
<script src="https://gist.github.com/viebel/8cb19d258fea39a64146721ce50603d0.js"></script>
++++
--

[%step]
--
To kliplisfy the gist, we use `data-gist-id` with the id of the gist - including the username.

Here is how it is included in the current presentation (check the page source!):

[.text]
----
<pre><code class="clj" data-gist-id="viebel/8cb19d258fea39a64146721ce50603d0">
</code></pre>
----
--

[%step]
--
Here is the klipsified gist:
++++
<pre><code class="clj" data-gist-id="viebel/8cb19d258fea39a64146721ce50603d0">
</code></pre>
++++
--

include::klipse.adoc[]
++++
<script src="https://cdnjs.cloudflare.com/ajax/libs/react/15.5.4/react-with-addons.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/react/15.5.4/react-dom.min.js"></script>
++++
